baseURL = "https://gdmgent-1819-csse2.github.io/04-ssg-nawatend/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "MyNawTheme"
pygmentsStyle="monokai"
pygmentsCodeFences=true
publishDir = "../docs"